# Generated by Django 5.0.6 on 2024-07-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
