version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    command: >
      sh -c '
        python manage.py migrate &&
        pytest
      '
    volumes:
      - ./backend:/code
    env_file:
      - .env
      - .env.test
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
