FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /code

# Install pip
RUN pip install --upgrade pip

# Copy only requirements to cache dependencies layer
COPY requirements.txt /code/
COPY requirements.test.txt /code/

# Install project dependencies
RUN pip install -r /code/requirements.txt
RUN pip install -r /code/requirements.test.txt

# Copy the project files
COPY . /code/
