FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /code

# Install pip
RUN pip install --upgrade pip

# Copy only requirements to cache dependencies layer
COPY requirements.txt /code/

# Install project dependencies
RUN pip install -r /code/requirements.txt

# Copy the project files
COPY . /code/

# Run the application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]
