name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create .env file
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "DJANGO_ENV=${{ secrets.DJANGO_ENV }}" >> .env.test
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env.test
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env.test

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8 --config=backend/.flake8 .

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.test.yml up -d

      - name: Run tests
        run: docker compose -f docker-compose.test.yml run backend pytest
